default:
  image: registry.gitlab.com/basiliq/dockerfiles

variables:
  RUSTFLAGS: -C link-dead-code

stages:
  - test

build_and_test_rust:
  stage: test
  services:
    - name: postgres:latest
      alias: postgres
  variables:
    POSTGRES_DB: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_HOST_AUTH_METHOD: trust
    DATABASE_URL: postgres://postgres:postgres@postgres/postgres
    BASILIQ_DATABASE_URL: postgres://postgres:postgres@postgres/postgres
    NAME: ciboulette2postgres
  before_script:
    - mkdir -p .git/hooks
  script:
    - cargo fmt -- --check
    - cargo clippy -- -D warnings
    - cargo build --all-targets
    - cargo test
  after_script:
    - for file in $(find target/debug/deps -executable \( -name "$(basename $NAME)-*" -o -name "mod-*" \) );
      do
        echo "Running $file";
        mkdir -p "target/cov/$(basename $file)";
        kcov "target/cov/$(basename $file)" --exclude-pattern="/.cargo,/usr/lib,$PWD/src/tests,$PWD/src/builder/tests" $file;
      done
    - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN -s target/cov
